name: practice_flutter_application_35
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_fonts: ^6.3.3
  get_it: ^9.2.0
  delightful_toast: ^1.0.2
  image_picker: ^1.2.1
  firebase_storage: ^13.0.5
  path: ^1.9.1
  firebase_database: ^12.1.1
  cloud_firestore: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
