name: practice_flutter_application_7
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.3
  icons_plus: ^5.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/1/1.jpg
    - images/1/0.jpg
    - images/1/2.jpg
    - images/1/3.jpg
    - images/1/4.jpg
    - images/1/5.jpg
    - images/1/6.jpg
    - images/2/1.jpg
    - images/2/2.webp
    - images/2/3.jpg
    - images/2/4.jpg
    - images/2/5.webp
    - images/2/6.jpg
    - images/2/7.jpg
    - images/8.png
    - images/snowpiercer_back.webp
    - images/snowpiercer.webp
    - images/bye.png
    - images/hi.webp
    - images/no 2.png
    - images/no 3.png
    - images/no 4.png
    - images/22.jpg
    - images/33.jpg
    - images/44.jpg
